```{R}
########################### Readme ###############################
#
#   Author:       Tim Siwula
#   Proposal:     http://bit.ly/2gcCLQ4
#   Kaggle:       http://bit.ly/2gMVpPG
#   Github:       http://bit.ly/2gZoTwy
#   Data:         http://bit.ly/2fQ0LHW
#
##################################################################
```

```{R}
########################### Notes ################################
# clear workspace ----> rm(list = ls())
#
####################################################################################
```
```{R}
########################### SET UP DATABASE CONNECTION ############################
# SET UP DATABASE CONNECTION
require("RPostgreSQL")    #install.packages("RPostgreSQL")
driver <- dbDriver("PostgreSQL")   # loads the PostgreSQL driver

# creates a connection to the postgres database
# note that "con" will be used later in each connection to the database
connection <- dbConnect(driver, dbname = "clickprediction",
                 host = "localhost", port = 5432,
                 user = "admin", password = "admin")
# confirm the tables are accessible
dbExistsTable(connection, "clicks_train")  
##################################################################################
```

```{R}
########################### QUERY THE DATABASE ##################################
# QUERY THE DATABASE
# 1) 
# try to find features related to ad_id.
# here we join click_train and promoted-content with ad_id.

# look at clicks_train first
getClicksTrain="select * from clicks_train limit 10 "
clicks_train = dbGetQuery(connection, getClicksTrain)
clicks_train

# look at promoted_content next
getPromotedContent="select * from promoted_content limit 10"
promoted_content = dbGetQuery(connection, getPromotedContent)
promoted_content

#TODO
#remove campagin and adversider id
#advertiser_id
#campiagn_id

# join click_train and promoted-content with ad_id new table
# 500k apears to be stable with rstudio.
join_query = "
select t.display_id, t.ad_id, t.clicked, d.document_id,
d.topic_id, d.confidence_level
from clicks_train t, promoted_content p, documents_topics d
where t.ad_id = p.ad_id and p.document_id = d.document_id 
limit 500000;"
merged_table=dbGetQuery(connection, join_query)
head(merged_table, 3)
dim(merged_table)
####################################################################################
```

```{R}
########################### CREATE AND WRITE NEW TABLE #############################
# CREATE AND WRITE NEW TABLE
dbWriteTable(connection, "merged_table", merged_table, row.names=FALSE)

# look at the new table
getMergedTable="select * from merged_table limit 500000"

new_table = dbGetQuery(connection, getMergedTable)

# list the structure of mydata
str(new_table)
####################################################################################
```

```{R}
########################### GET 50/50 CLICKED ######################################

ones = new_table[new_table$clicked>0, 50000]
length(ones)
length(new_table)

onesVersion2 = ones = subset(new_table, clicked>0)
dim(onesVersion2)

zeros = subset(new_table, clicked < 1)
dim(zeros)

undersampled_zeros = zeros[sample(nrow(zeros), 50000), ]
table(undersampled_zeros$clicked)
table(ones$clicked)
dim(undersampled_zeros)
dim(ones)
names(undersampled_zeros)
names(ones)

final_dataset <- merge(undersampled_zeros, ones, all.x=TRUE, all.y=TRUE)

# FINAL DATA SET
dim(final_dataset)
head(final_dataset, n=5)
####################################################################################
```

```{R}
########################### CREATE TRAINING AND TEST SET ###########################
# CREATE TRAINING AND TEST SET
partition_size = floor(0.80 * nrow(final_dataset)) ## 80% of the sample size
set.seed(123) ## set the seed to make your partition reproductible
partition_index <- sample(seq_len(nrow(final_dataset)), size = partition_size)
local_train_set <- final_dataset[partition_index, ]
local_test_set <- final_dataset[-partition_index, ]

# LOCAL TEST SET
dim(local_test_set)
head(local_test_set, n=5)

# LOCAL TRAIN SET
dim(local_train_set)
head(local_train_set, n=5)
#########################################################################
```

```{R}
########################### RANDOM FORESTS ###########################

##########################   INIT       ##############################
#install.packages('randomForest', repos="http://cran.r-project.org")
require(randomForest)
set.seed(101)
dim(final_dataset)
attach(final_dataset)
#########################################################################

##########################   FIT W/RESPONSE CLICKED        ##############
install.packages("tree")
library(ISLR)
library(tree)
attach(final_dataset)
train=sample(local_train_set, length(local_train_set))
myTree=tree(clicked~.-clicked,final_dataset)
summary(myTree)
plot(myTree)
text(myTree,pretty=0)



#> set.seed(2) 
#> train=sample (1: nrow(Carseats), 200) 
#> Carseats .test=Carseats [-train,] 
#> High.test=High[-train] > tree.carseats =tree(High∼.-Sales, Carseats ,subset=train) 
#> tree.pred=predict(tree.carseats ,Carseats .test ,type="class") 
#> table(tree.pred ,High.test)




#########################################################################
##########################   FIT REGRESSION TREE TO FINAL_DATA_SET   ##############
#1 CREATE A TRAINING SET
# CREATE TRAINING AND TEST SET
partition_size = floor(0.80 * nrow(final_dataset)) ## 80% of the sample size
set.seed(123) ## set the seed to make your partition reproductible
partition_index <- sample(seq_len(nrow(final_dataset)), size = partition_size)
local_train_set <- final_dataset[partition_index, ]
local_test_set <- final_dataset[-partition_index, ]

train=sample( 1:nrow(final_dataset), floor(0.80 * nrow(final_dataset) ) )

# LOCAL TEST SET
dim(local_test_set)
head(local_test_set, n=5)

# LOCAL TRAIN SET
dim(local_train_set)
head(local_train_set, n=5)

#2 FIT TREE TO TRAINING SET
tree.final=tree(clicked~.,final_dataset,subset=train)
summary(tree.final)
plot(tree.final)
text(tree.final,pretty=0)
tree.final
#########################################################################



#########################################################################
```


# TODO
# create test set after train set
# 1) logistic regession glm
# 2) random forests model
# get mean test error ----> mean(pred == test_Set$clicked)
# test predicted vs total using table() gets your true positives etc
# compare true positives vs all others
# TP/(TP+FP)
# 3) then cross validate results

hist(new_table$clicked)
length(new_table$clicked[new_table$clicked>0])

# skewness library pkg from r called e1071
#install.packages("e1071")
library(e1071)
skewness(new_table$clicked)




# TODO
# include in presentatinon and plot to show skewness



new_table[new_table$clicked=0] # only get 50k from the popular class
?sample
#same into data frame and then join
#sample(new_table, 50000, ...)
#zeros <— sample(new_table, 50000, ...)


########################### CREATE DECISION TREE MODEL #############################
#3) Models and response
#Models to consider:
#Start with the classification problem first - easier problem - start with decision trees, random forests and #bagging
#Then switch to regression
```{r}
# CREATE DECISION TREE MODEL
require(tree)
str(new_table)
hist(new_table$confidence_level)
hist(new_table$clicked)
hist(new_table$display_id)
hist(new_table$ad_id)
hist(new_table$document_id)
hist(new_table$topic_id)
attach(new_table)
confidence20=ifelse(new_table$confidence_level>=0.2,"Yes","No")
str(confidence20)
new_table=data.frame(new_table, confidence20)
tree.local.train.c20=tree(confidence20~.-new_table$confidence_level,data=new_table)
summary(tree.local.train.c20)
plot(tree.local.train.c20)
text(tree.local.train.c20,pretty=0)
```
##############################################################################

########################### Setup ################################
---
output: pdf_document
---
```{R}
# SETUP
library(knitr)
library(markdown)
#transform the .Rmd to a markdown (.md) file.
knit('tims_script.Rmd')
```
####################################################################################